### ISSUE TITLE
Momentary game freeze when mounting up

### ISSUE THREAD

**Issue by Vilacard** [DanSheps/Bestride#73]
My game freezes for maybe half a second when mounting up. It seems to be something that was changed in the 1.0.1 release (and still present in 1.0.8), but is not in the 0.0.11 release.

I'm having a hard time tracking down what causes it. It's an addon conflict of some sort, as it works fine with everything but Bestride and Addon Control Panel disabled. I've tried slowly disabling addons to narrow it down, and it does get better, but when I think I've found it and enabled everything else the issue comes back. For now I think I'll stick to the 0.0.11 release, but here's my addon list if it helps:

Addon Control Panel
Advanced Interface Options
Altoholic
ArcHUD3
Ark Inventory
Astral Keys
Auctionator
AutoLootPlus
AzeriteTooltip
BattlegroundTargets
Bestride
Bindpad
Broker DurabilityInfo/Everything/MicroMenu
Can I Mog It?
ChocolateBar
Clique
Datastore
DBM
DataStore
DBM
DejaCharacterStats
Details
Easy Scrap
Ebony's Multiboxing Assistant
Examiner
Exorsus Raid Tools
Flash Task Bar
Garrison Mission Manager
GottaGoFast
Grid2
I_Hear_You_Whisper/I_Hear_You_BN
In Progress Missions
ISBoxer
KUI
LargerMacroIconSelection
Master Plan
Method Alt Manager
Mik's Scrolling Battle Text
MoveAnything
OPie
Paste
Pawn
Prat
Premade Groups Filter
Quartz
QuickQuest
Raider.io
RangeDIsplay
RCLootCouncil
Reagent Banker
RelicInspector
Rematch
SellJunk
Shadowed Unit Frames
SharedMedia
SimPermut
Simulationcraft
SlashIn
SPTimers
tdBattlePetScript
TomTom
TooltipOnMouse
Twintop's Insanity Bar
WeakAuras 2
WhisperWhisper
World Quests List
Lib: Ace3/Lib: SharedMedia-3.0

**Comment by Mindlessgalaxy** [comment]
Hi,

Just so you know for me, I have around 300 addons and no issues, I also know how hard it is to work out which ones.  I will list the ones I know have known issues, but don't ever seem to have been fixed or corrected for whatever reasons?

**_Broker Everything_** is handy - Got rid of it and replaced it with others that do same things and made huge difference for me.
**_Weak Auras 2_** - Is great and love it, but uses to much in the way of system resources and if you haven't got a top notch machine they will often tell you themselves to maybe not use it.  Again others out there to try, like TellmeWhen, but of course it means learning a new one and setting it up.
**_Addon Control Panel_** - This one has always been a funny one for me, but no one else, just mentioning it for your sake to try.
**_Advanced Interface Options_** - Same as the one above, although this one causes me more trouble than it does.
_**Ark Inventory**_ - This one is awesome and if you have the current version it works well for me, although there are sometimes issues for people with hanging like you have described above.
**_Auctionator_** -  Love this one as well, but since stopping using it, my game has been smoother, but cannot say for sure if it was this one or another, as I got rid of a few at the same time, sorry about that.
_**_RelicInspector_**_ - I know this one can cause issues for some, but really not that many, I got rid of it, as it isn't really relevant anymore with BFA and not needed. But that is of course your choice.
**_Lib: Ace3/Lib: SharedMedia-3.0_** - Just make sure these are current and preferably the alpha versions of ACE3 as there are known issues as well in there.  Shared Media should be fine.

The rest are ok, although there are several I do not know or have never used.  I would suggest disabling all the ones above that I listed and see what happens for you.  If that works then you are on the right track and I hope it does for your sake and hopefully one you don't need.  Then just keep doing that.  Sometimes the only way to work out which one is turning them off in batches and I simply use the alphabet to work out which ones to unmark etc first.  Good luck and I hope it helps you.

One last suggestion, if you do think it is Bestride then disable all the other addons and only have bestride enabled and see what happens.  If it works it is not this addon.  Before you do that, the best thing is go to a new realm if you are able or one you don't use much and then disable all the addons, or make a backup of your WTF folder and go from there, Or you will have to reselect every single addon for every single toon that you want it on.  The moment you unselect all it is stuffed and I really resent that lol,  Hope that also helps as it always drives me crazy or nuts when I do forget to do that.  It is essential in my opinion only.

Good Luck and hope you don't mind my opinion and trying to help.

Mindlessgalaxy.

**Comment by Vilacard** [comment]
I did already try disabling all my addons except Bestride and AddonControlPanel, and it works fine. I'm just having trouble narrowing it down to what exactly is causing the conflict: I'll disable a bunch bit by bit and it gets better, but when I finally think I find the issue and reenable everything but that mod the issue comes back.

**Comment by Mindlessgalaxy** [comment]
Sorry about that, I am not sure which one it must be, be aware that I have had on very rare occasion 2 addons which caused the same problem and really confused me. Just so you know is all and good luck,

Mindlessgalaxy

**Comment by Ragnar-F** [comment]
Same issue. It also causes barely noticeable freezes when I have disabled all addons except BeStride. It seems that the more addons I reactivate, the longer the freeze.

**Comment by DanSheps** [comment]
I thought about this for a little bit, it could be the garbagecollection in the game.  I will disable it and let you know.

**Comment by Ragnar-F** [comment]
Commenting out `collectgarbage()` helps (at least for me).

**Comment by DanSheps** [comment]
Thanks, that is helpful.

Could you try moving it into the postclick section and uncommenting it?

I will have to see if there is a way to handle it better.

Thanks

**Comment by Vilacard** [comment]
Commenting out collectgarbage() seems to have fixed the issue for me as well. Not sure which you wanted to comment out (There were like 4 of them I think?), so I did all of them.

**Comment by DanSheps** [comment]
Thanks,

I will try some profiling of the addon and see if there are any major issues with removing the collectgarbage(), if not I think we will probably be good.
